Authorization using pundits and classes
AdolfoNava/industrial-photogram-authorization pull request #2
Opened 2024-07-17 14:52 UTC by AdolfoNava

2024-07-17 18:38 UTC, ajmompr requested changes
Review the assignment requirements and ensure that you are meeting all points. You are currently missing policies and the existing policies are not fully implemented

- Set up policies for the `Photos`, `Users`, `Comments`, and `FollowRequests` controllers.
- We are not requiring a policy for Likes at this point since it's not fully implemented.
- Ask a fellow trainee to review your PR as part of their "giving a code review" assignment.
 

Check list:
- Have you "secured by default"? E.g. calling `verify_authorized` and `verify_policy_scoped` after action in the application controller.
- Have you called `authorize` for each action in each controller?
- Have you set up policies for each action in each controller?
- Have you made sure everything is working in the live preview?

2024-07-17 18:38 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, except: :index
How are you accounting for Devise?

2024-07-17 18:38 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_policy_scoped, only: :index
How are you accounting for Devise?

2024-07-17 18:38 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    authorize @photo
Nice job! You can use a before action in each of your controllers to authorize an instance of photo or a photo class object

2024-07-17 18:38 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    def ensure_current_user_is_owner
This is unnecessary. You can ensure that current user is owner via your photo policy

2024-07-17 18:38 UTC, ajmompr commented on app/policies/application_policy.rb
> +class ApplicationPolicy
good use of pundit generator

2024-07-17 18:38 UTC, ajmompr commented on app/policies/photo_policy.rb
> +class PhotoPolicy < ApplicationPolicy
Read through the lesson and ensure that your policies encapsulate logic for all actions. This is incomplete

2024-07-17 18:38 UTC, ajmompr commented on app/policies/user_policy.rb
> +  def initialize(current_user, user)
incomplete policy

2024-07-17 18:38 UTC, ajmompr commented on app/policies/photo_policy.rb
Missing policies.

2024-07-22 20:25 UTC, ajmompr requested changes
Fix your comment controller than it should be okay for full credit!

2024-07-22 20:25 UTC, ajmompr commented on app/controllers/application_controller.rb
> +  after_action :verify_authorized, unless: :devise_controller?
good job accounting for devise

2024-07-22 20:25 UTC, ajmompr commented on app/controllers/comments_controller.rb
> +  before_action{authorize( @comments || Comment)}
Should be @ comment (singular!). Is your app working for adding comments?

2024-07-22 20:25 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +  before_action :ensure_user_is_authorized, only: [:show]
redundant if adding authorize before action on line 5

2024-07-22 20:25 UTC, ajmompr commented on app/controllers/photos_controller.rb
> +    def ensure_user_is_authorized
redundant but OK

2024-07-22 20:25 UTC, ajmompr commented on app/controllers/users_controller.rb
> +  before_action{authorize( @user || User)}
good

2024-07-23 17:14 UTC, ajmompr approved these changes

2024-07-24 15:54 UTC, jrzricardo approved these changes
looks good boss

2024-07-24 15:54 UTC, jrzricardo commented on app/views/users/show.html.erb
clean

2024-07-24 15:54 UTC, jrzricardo commented on app/policies/user_policy.rb
users are a go

2024-07-24 15:54 UTC, jrzricardo commented on app/policies/photo_policy.rb
you don't have to include index? since false is set as default in the inherited Application Policy, that being said, it won't break anything.

2024-07-24 15:56 UTC, merged